export { openStore, closeStore, saveStore, DEFAULT_DB_PATH, getSql, type Store } from './db.js';
export {
  insertPrompt,
  getRecentPrompts,
  deleteProjectPrompts,
  deleteAllPrompts,
  pruneOlderThan,
  getPromptStats,
  type InsertParams,
  type PromptStats,
  type RecentPrompt,
} from './prompts.js';
export { getConfig, setConfig, getAllConfig, isConfigSet, deleteConfig, DEFAULT_CONFIG } from './config.js';
export { redactSecrets } from './redact.js';
export { upsertProject, getProject, listProjects, setDetectedLanguage, type ProjectRecord, type UpsertProjectParams } from './projects.js';
export {
  insertSkippedSession,
  getSkippedSessions,
  getSkippedSessionCount,
  deleteSkippedSession,
  deleteAllSkippedSessions,
  deleteAllSkippedSessionsGlobal,
  pruneSkippedSessions,
  type SkippedSessionRecord,
  type InsertSkippedSessionInput,
} from './skipped-sessions.js';
export { importHistoricalPrompts } from './historical-import.js';
export {
  getUserDepthLevel,
  listUserDepthLevels,
  upsertUserDepthLevel,
  type UserDepthRow,
} from './user-depth-level.js';
export {
  isEnvProbeEnabled,
  setProjectEnvFacts,
  getProjectEnvFacts,
  setMachineFacts,
  getMachineFacts,
  clearProjectEnvFacts,
  purgeAllEnvFacts,
  ENV_PROBE_ENABLED_KEY,
  MACHINE_FACTS_KEY,
  type StoredFacts,
} from './env-facts.js';
export {
  upsertPendingAdvisory,
  getPendingAdvisory,
  markAdvisoryShown,
  type PendingAdvisory,
  type UpsertPendingAdvisoryInput,
} from './pending-advisories.js';
export {
  queryRelevantPromptEnhancementMemory,
  recordPromptEnhancementMemoryEvidence,
  markPromptEnhancementMemoryUsed,
  recordPromptEnhancementMemoryFeedback,
  recordPromptEnhancementSourceUse,
  recordPromptEnhancementGeneratedOrigin,
  recordPromptEnhancementFeedbackEvent,
  recordPromptEnhancementPreparedBody,
  recordPromptEnhancementExposure,
  recordPromptEnhancementAction,
  decayPromptEnhancementMemory,
  prunePromptEnhancementMemory,
  prunePromptEnhancementFeedbackAndSourceUse,
  prunePromptEnhancementRows,
  deletePromptEnhancementMemoryForProject,
  deleteAllPromptEnhancementMemory,
  deleteAllPromptEnhancementRows,
  deletePromptEnhancementProjectRows,
  resetPromptEnhancementProjectRows,
  resetAllPromptEnhancementRows,
  deletePromptEnhancementFeedbackForProject,
  deleteAllPromptEnhancementFeedback,
  deletePromptEnhancementSourceUseForProject,
  deleteAllPromptEnhancementSourceUse,
  setPromptEnhancementStatus,
  deletePromptEnhancementStatusForProject,
  deleteAllPromptEnhancementStatus,
  getPromptEnhancementMemory,
  getPromptEnhancementMemoryStats,
  getPromptEnhancementStoreStatus,
  getPromptEnhancementDebugSummary,
  resolvePromptEnhancementGeneratedOrigin,
  getPromptEnhancementFeedbackSummary,
  getPromptEnhancementSourceUseSummary,
  getPromptEnhancementSchemaVersionState,
  type PromptEnhancementFeedbackCategory,
  type PromptEnhancementMemoryRow,
  type PromptEnhancementMemoryEvidenceInput,
  type PromptEnhancementMemoryUseInput,
  type PromptEnhancementLearningEligibilityFlags,
  type PromptEnhancementSourceUseInput,
  type PromptEnhancementGeneratedOriginInput,
  type PromptEnhancementFeedbackInput,
  type PromptEnhancementPreparedBodyInput,
  type PromptEnhancementExposureInput,
  type PromptEnhancementActionInput,
  type PromptEnhancementStatusInput,
  type PromptEnhancementStoreStatus,
  type PromptEnhancementPruneResult,
  type PromptEnhancementGeneratedOriginResolution,
  type PromptEnhancementFeedbackSummary,
  type PromptEnhancementSourceUseSummary,
} from './prompt-enhancement.js';
